name: ${COMPOSE_PROJECT_NAME:-assessment_app}

services:
  web:
    image: ${APP_IMAGE:-ghcr.io/fstelte/assessment-app:latest}
    pull_policy: always
    env_file:
      - ../.env.production
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-scaffold}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-scaffold}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-scaffold}
      DATABASE_URL: "postgresql+psycopg://${POSTGRES_USER:-scaffold}:${POSTGRES_PASSWORD:-scaffold}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-scaffold}"
      FLASK_ENV: production
    volumes:
      - ../instance:/app/instance
      #- ../migrations:/app/migrations
      - maintenance-page:/maintenance
    restart: unless-stopped

  gateway:
    image: nginx:1.27-alpine
    depends_on:
      - web
    env_file:
      - ../.env.production
    environment:
      CERTBOT_ENABLED: ${CERTBOT_ENABLED:-false}
      CERTBOT_FORCE_HTTPS: ${CERTBOT_FORCE_HTTPS:-true}
      CERTBOT_PRIMARY_DOMAIN: ${CERTBOT_PRIMARY_DOMAIN:-}
      CERTBOT_ADDITIONAL_DOMAINS: ${CERTBOT_ADDITIONAL_DOMAINS:-}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - maintenance-page:/usr/share/nginx/html/maintenance
      - ./nginx/entrypoint.d:/docker-entrypoint.d:ro
      - gateway-logs:/var/log/nginx
      - crowdsec-bouncer:/etc/nginx/crowdsec
    ports:
      - "8000:8000"
    restart: unless-stopped


  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-scaffold}
      POSTGRES_USER: ${POSTGRES_USER:-scaffold}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-scaffold}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-scaffold} -d ${POSTGRES_DB:-scaffold}"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped


volumes:
  postgres-data:
  maintenance-page:
  gateway-logs:
  crowdsec-bouncer:
