version: '3.8'

services:
  bia-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=aVerySecurePasswordSh0uldBeUsedH3r3!
      - SECRET_KEY=een_andere_geheime_sleutel_voor_flask
      - FLASK_ENV=development
    volumes:
      - ../instance:/app/instance
      - ../app:/app/app
      - ../static:/app/static
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s